### ISSUE TITLE
Supervisor Services 

### ISSUE THREAD

**Issue by UrielWo** [vsphere-tmm/Supervisor-Services#13]
Supervisor Services are available with Supervisor Clusters enabled using NSX-ALB?

**Comment by rguske** [comment]
Hi @UrielWo, with vSphere 8 Update 1, which isn't GA'ed yet, the Supervisor Services can be used with the vSphere Distributed Switch (vSphere networking). Prior this version, VMware NSX is required.

**Comment by UrielWo** [comment]
thank you!

**Comment by rguske** [comment]
@UrielWo If your Q is answered, please go ahead and close the issue. Thy
