### ISSUE TITLE
Day-2 operations Supervisor Services

### ISSUE THREAD

**Issue by rguske** [vsphere-tmm/Supervisor-Services#14]
Hi,
in terms of day-2 ops. What is the right way to apply intended changes to an existing and applied Supervisor Service configuration? Let's take Harbor as an example. I want to extend an existing `pvc` resource in order to make more capacity available. I was not able to simply apply an adjusted `harbor-data-values.yaml` file to an existing instance. I did the changes by editing the resource itself using `k -n svc-harbor-domain-c8 edit pvc harbor-registry`. It worked out so far:
![image](https://user-images.githubusercontent.com/31652019/234029161-a5668aa0-53fe-46f0-bf5d-4c54f99c7c7b.png)

But I wonder if this "manually" applied adjustment will persist?

Thy

**Comment by fstrudel** [comment]
@rguske You should be able to go to the update screen to "update" the Supervisor Service and just change the YAML config values (and keep the same version). Did that fail for you?

**Comment by fstrudel** [comment]
@rguske you need to navigate to the Supervisor running the service first:
 
![image](https://user-images.githubusercontent.com/1244567/234338429-138f0f12-1e06-47a8-9c3f-14ba66827e32.png)

Then you can edit the service configuration by clicking Edit after selecting the service:
![vSphere Client 2023-04-25 09-05-31](https://user-images.githubusercontent.com/1244567/234338526-c0f69832-db67-4dd9-8bed-b5c18606667d.png)

And you can change the configuration:
![image](https://user-images.githubusercontent.com/1244567/234337820-7c49a0a2-3402-429e-976e-d779c3bf6c63.png)

**Comment by rguske** [comment]
Great! Thanks for the clarification Fanny 🙏🏻
